import { Blueprint } from '@prisma/client';

export const BLUEPRINTS_AVAILABLE: Blueprint[] = [
  {
    id: 1,
    name: 'blueprint-1',
    description: 'blueprint-1',
    tips: 'tips-1',
    category: 'category-1',
    ingredients: 'ingredients-1',
    imageUrl: 'https://i.imgur.com/1.jpg',
    reward: 1,
    deliveryTime: 1,
    createdAt: new Date(),
  },
  {
    id: 2,
    name: 'blueprint-2',
    description: 'blueprint-2',
    tips: 'tips-2',
    category: 'category-2',
    ingredients: 'ingredients-2',
    imageUrl: 'https://i.imgur.com/2.jpg',
    reward: 2,
    deliveryTime: 2,
    createdAt: new Date(),
  },
  {
    id: 3,
    name: 'blueprint-3',
    description: 'blueprint-3',
    tips: 'tips-3',
    category: 'category-3',
    ingredients: 'ingredients-3',
    imageUrl: 'https://i.imgur.com/3.jpg',
    reward: 3,
    deliveryTime: 3,
    createdAt: new Date(),
  },
  {
    id: 4,
    name: 'blueprint-4',
    description: 'blueprint-4',
    tips: 'tips-4',
    category: 'category-4',
    ingredients: 'ingredients-4',
    imageUrl: 'https://i.imgur.com/4.jpg',
    reward: 4,
    deliveryTime: 4,
    createdAt: new Date(),
  },
  {
    id: 5,
    name: 'blueprint-5',
    description: 'blueprint-5',
    tips: 'tips-5',
    category: 'category-5',
    ingredients: 'ingredients-5',
    imageUrl: 'https://i.imgur.com/5.jpg',
    reward: 5,
    deliveryTime: 5,
    createdAt: new Date(),
  },
  {
    id: 6,
    name: 'blueprint-6',
    description: 'blueprint-6',
    tips: 'tips-6',
    category: 'category-6',
    ingredients: 'ingredients-6',
    imageUrl: 'https://i.imgur.com/6.jpg',
    reward: 6,
    deliveryTime: 6,
    createdAt: new Date(),
  },
  {
    id: 7,
    name: 'blueprint-7',
    description: 'Descrição para blueprint 7',
    tips: 'Dicas para blueprint 7',
    category: 'Categoria 7',
    ingredients: 'Ingredientes para blueprint 7',
    imageUrl: 'https://i.imgur.com/7.jpg',
    reward: 7,
    deliveryTime: 7,
    createdAt: new Date(),
  },
  {
    id: 8,
    name: 'blueprint-8',
    description: 'Descrição para blueprint 8',
    tips: 'Dicas para blueprint 8',
    category: 'Categoria 8',
    ingredients: 'Ingredientes para blueprint 8',
    imageUrl: 'https://i.imgur.com/8.jpg',
    reward: 8,
    deliveryTime: 8,
    createdAt: new Date(),
  },
  {
    id: 9,
    name: 'blueprint-9',
    description: 'Descrição para blueprint 9',
    tips: 'Dicas para blueprint 9',
    category: 'Categoria 9',
    ingredients: 'Ingredientes para blueprint 9',
    imageUrl: 'https://i.imgur.com/9.jpg',
    reward: 9,
    deliveryTime: 9,
    createdAt: new Date(),
  },
  {
    id: 10,
    name: 'blueprint-10',
    description: 'Descrição para blueprint 10',
    tips: 'Dicas para blueprint 10',
    category: 'Categoria 10',
    ingredients: 'Ingredientes para blueprint 10',
    imageUrl: 'https://i.imgur.com/10.jpg',
    reward: 10,
    deliveryTime: 10,
    createdAt: new Date(),
  },
  {
    id: 11,
    name: 'blueprint-11',
    description: 'Descrição para blueprint 11',
    tips: 'Dicas para blueprint 11',
    category: 'Categoria 11',
    ingredients: 'Ingredientes para blueprint 11',
    imageUrl: 'https://i.imgur.com/11.jpg',
    reward: 11,
    deliveryTime: 11,
    createdAt: new Date(),
  },
  {
    id: 12,
    name: 'blueprint-12',
    description: 'Descrição para blueprint 12',
    tips: 'Dicas para blueprint 12',
    category: 'Categoria 12',
    ingredients: 'Ingredientes para blueprint 12',
    imageUrl: 'https://i.imgur.com/12.jpg',
    reward: 12,
    deliveryTime: 12,
    createdAt: new Date(),
  },
  {
    id: 13,
    name: 'blueprint-13',
    description: 'Descrição para blueprint 13',
    tips: 'Dicas para blueprint 13',
    category: 'Categoria 13',
    ingredients: 'Ingredientes para blueprint 13',
    imageUrl: 'https://i.imgur.com/13.jpg',
    reward: 13,
    deliveryTime: 13,
    createdAt: new Date(),
  },
  {
    id: 14,
    name: 'blueprint-14',
    description: 'Descrição para blueprint 14',
    tips: 'Dicas para blueprint 14',
    category: 'Categoria 14',
    ingredients: 'Ingredientes para blueprint 14',
    imageUrl: 'https://i.imgur.com/14.jpg',
    reward: 14,
    deliveryTime: 14,
    createdAt: new Date(),
  },
  {
    id: 15,
    name: 'blueprint-15',
    description: 'Descrição para blueprint 15',
    tips: 'Dicas para blueprint 15',
    category: 'Categoria 15',
    ingredients: 'Ingredientes para blueprint 15',
    imageUrl: 'https://i.imgur.com/15.jpg',
    reward: 15,
    deliveryTime: 15,
    createdAt: new Date(),
  },
  {
    id: 16,
    name: 'blueprint-16',
    description: 'Descrição para blueprint 16',
    tips: 'Dicas para blueprint 16',
    category: 'Categoria 16',
    ingredients: 'Ingredientes para blueprint 16',
    imageUrl: 'https://i.imgur.com/16.jpg',
    reward: 16,
    deliveryTime: 16,
    createdAt: new Date(),
  },
  {
    id: 17,
    name: 'blueprint-17',
    description: 'Descrição para blueprint 17',
    tips: 'Dicas para blueprint 17',
    category: 'Categoria 17',
    ingredients: 'Ingredientes para blueprint 17',
    imageUrl: 'https://i.imgur.com/17.jpg',
    reward: 17,
    deliveryTime: 17,
    createdAt: new Date(),
  },
  {
    id: 18,
    name: 'blueprint-18',
    description: 'Descrição para blueprint 18',
    tips: 'Dicas para blueprint 18',
    category: 'Categoria 18',
    ingredients: 'Ingredientes para blueprint 18',
    imageUrl: 'https://i.imgur.com/18.jpg',
    reward: 18,
    deliveryTime: 18,
    createdAt: new Date(),
  },
  {
    id: 19,
    name: 'blueprint-19',
    description: 'Descrição para blueprint 19',
    tips: 'Dicas para blueprint 19',
    category: 'Categoria 19',
    ingredients: 'Ingredientes para blueprint 19',
    imageUrl: 'https://i.imgur.com/19.jpg',
    reward: 19,
    deliveryTime: 19,
    createdAt: new Date(),
  },
  {
    id: 20,
    name: 'blueprint-20',
    description: 'Descrição para blueprint 20',
    tips: 'Dicas para blueprint 20',
    category: 'Categoria 20',
    ingredients: 'Ingredientes para blueprint 20',
    imageUrl: 'https://i.imgur.com/20.jpg',
    reward: 20,
    deliveryTime: 20,
    createdAt: new Date(),
  },
  {
    id: 21,
    name: 'blueprint-21',
    description: 'Descrição para blueprint 21',
    tips: 'Dicas para blueprint 21',
    category: 'Categoria 21',
    ingredients: 'Ingredientes para blueprint 21',
    imageUrl: 'https://i.imgur.com/21.jpg',
    reward: 21,
    deliveryTime: 21,
    createdAt: new Date(),
  },
  {
    id: 22,
    name: 'blueprint-22',
    description: 'Descrição para blueprint 22',
    tips: 'Dicas para blueprint 22',
    category: 'Categoria 22',
    ingredients: 'Ingredientes para blueprint 22',
    imageUrl: 'https://i.imgur.com/22.jpg',
    reward: 22,
    deliveryTime: 22,
    createdAt: new Date(),
  },
  {
    id: 23,
    name: 'blueprint-23',
    description: 'Descrição para blueprint 23',
    tips: 'Dicas para blueprint 23',
    category: 'Categoria 23',
    ingredients: 'Ingredientes para blueprint 23',
    imageUrl: 'https://i.imgur.com/23.jpg',
    reward: 23,
    deliveryTime: 23,
    createdAt: new Date(),
  },
  {
    id: 24,
    name: 'blueprint-24',
    description: 'Descrição para blueprint 24',
    tips: 'Dicas para blueprint 24',
    category: 'Categoria 24',
    ingredients: 'Ingredientes para blueprint 24',
    imageUrl: 'https://i.imgur.com/24.jpg',
    reward: 24,
    deliveryTime: 24,
    createdAt: new Date(),
  },
  {
    id: 25,
    name: 'blueprint-25',
    description: 'Descrição para blueprint 25',
    tips: 'Dicas para blueprint 25',
    category: 'Categoria 25',
    ingredients: 'Ingredientes para blueprint 25',
    imageUrl: 'https://i.imgur.com/25.jpg',
    reward: 25,
    deliveryTime: 25,
    createdAt: new Date(),
  },
  {
    id: 26,
    name: 'blueprint-26',
    description: 'Descrição para blueprint 26',
    tips: 'Dicas para blueprint 26',
    category: 'Categoria 26',
    ingredients: 'Ingredientes para blueprint 26',
    imageUrl: 'https://i.imgur.com/26.jpg',
    reward: 26,
    deliveryTime: 26,
    createdAt: new Date(),
  },
  {
    id: 27,
    name: 'blueprint-27',
    description: 'Descrição para blueprint 27',
    tips: 'Dicas para blueprint 27',
    category: 'Categoria 27',
    ingredients: 'Ingredientes para blueprint 27',
    imageUrl: 'https://i.imgur.com/27.jpg',
    reward: 27,
    deliveryTime: 27,
    createdAt: new Date(),
  },
  {
    id: 28,
    name: 'blueprint-28',
    description: 'Descrição para blueprint 28',
    tips: 'Dicas para blueprint 28',
    category: 'Categoria 28',
    ingredients: 'Ingredientes para blueprint 28',
    imageUrl: 'https://i.imgur.com/28.jpg',
    reward: 28,
    deliveryTime: 28,
    createdAt: new Date(),
  },
  {
    id: 29,
    name: 'blueprint-29',
    description: 'Descrição para blueprint 29',
    tips: 'Dicas para blueprint 29',
    category: 'Categoria 29',
    ingredients: 'Ingredientes para blueprint 29',
    imageUrl: 'https://i.imgur.com/29.jpg',
    reward: 29,
    deliveryTime: 29,
    createdAt: new Date(),
  },
  {
    id: 30,
    name: 'blueprint-30',
    description: 'Descrição para blueprint 30',
    tips: 'Dicas para blueprint 30',
    category: 'Categoria 30',
    ingredients: 'Ingredientes para blueprint 30',
    imageUrl: 'https://i.imgur.com/30.jpg',
    reward: 30,
    deliveryTime: 30,
    createdAt: new Date(),
  },
  {
    id: 31,
    name: 'blueprint-31',
    description: 'Descrição para blueprint 31',
    tips: 'Dicas para blueprint 31',
    category: 'Categoria 31',
    ingredients: 'Ingredientes para blueprint 31',
    imageUrl: 'https://i.imgur.com/31.jpg',
    reward: 31,
    deliveryTime: 31,
    createdAt: new Date(),
  },
  {
    id: 32,
    name: 'blueprint-32',
    description: 'Descrição para blueprint 32',
    tips: 'Dicas para blueprint 32',
    category: 'Categoria 32',
    ingredients: 'Ingredientes para blueprint 32',
    imageUrl: 'https://i.imgur.com/32.jpg',
    reward: 32,
    deliveryTime: 32,
    createdAt: new Date(),
  },
  {
    id: 33,
    name: 'blueprint-33',
    description: 'Descrição para blueprint 33',
    tips: 'Dicas para blueprint 33',
    category: 'Categoria 33',
    ingredients: 'Ingredientes para blueprint 33',
    imageUrl: 'https://i.imgur.com/33.jpg',
    reward: 33,
    deliveryTime: 33,
    createdAt: new Date(),
  },
  {
    id: 34,
    name: 'blueprint-34',
    description: 'Descrição para blueprint 34',
    tips: 'Dicas para blueprint 34',
    category: 'Categoria 34',
    ingredients: 'Ingredientes para blueprint 34',
    imageUrl: 'https://i.imgur.com/34.jpg',
    reward: 34,
    deliveryTime: 34,
    createdAt: new Date(),
  },
  {
    id: 35,
    name: 'blueprint-35',
    description: 'Descrição para blueprint 35',
    tips: 'Dicas para blueprint 35',
    category: 'Categoria 35',
    ingredients: 'Ingredientes para blueprint 35',
    imageUrl: 'https://i.imgur.com/35.jpg',
    reward: 35,
    deliveryTime: 35,
    createdAt: new Date(),
  },
  {
    id: 36,
    name: 'blueprint-36',
    description: 'Descrição para blueprint 36',
    tips: 'Dicas para blueprint 36',
    category: 'Categoria 36',
    ingredients: 'Ingredientes para blueprint 36',
    imageUrl: 'https://i.imgur.com/36.jpg',
    reward: 36,
    deliveryTime: 36,
    createdAt: new Date(),
  },
  {
    id: 37,
    name: 'blueprint-37',
    description: 'Descrição para blueprint 37',
    tips: 'Dicas para blueprint 37',
    category: 'Categoria 37',
    ingredients: 'Ingredientes para blueprint 37',
    imageUrl: 'https://i.imgur.com/37.jpg',
    reward: 37,
    deliveryTime: 37,
    createdAt: new Date(),
  },
  {
    id: 38,
    name: 'blueprint-38',
    description: 'Descrição para blueprint 38',
    tips: 'Dicas para blueprint 38',
    category: 'Categoria 38',
    ingredients: 'Ingredientes para blueprint 38',
    imageUrl: 'https://i.imgur.com/38.jpg',
    reward: 38,
    deliveryTime: 38,
    createdAt: new Date(),
  },
  {
    id: 39,
    name: 'blueprint-39',
    description: 'Descrição para blueprint 39',
    tips: 'Dicas para blueprint 39',
    category: 'Categoria 39',
    ingredients: 'Ingredientes para blueprint 39',
    imageUrl: 'https://i.imgur.com/39.jpg',
    reward: 39,
    deliveryTime: 39,
    createdAt: new Date(),
  },
  {
    id: 40,
    name: 'blueprint-40',
    description: 'Descrição para blueprint 40',
    tips: 'Dicas para blueprint 40',
    category: 'Categoria 40',
    ingredients: 'Ingredientes para blueprint 40',
    imageUrl: 'https://i.imgur.com/40.jpg',
    reward: 40,
    deliveryTime: 40,
    createdAt: new Date(),
  },
];
